backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: CMS - Create {{collection}} "{{slug}}"
    update: CMS - Update {{collection}} "{{slug}}"
    delete: CMS - Delete {{collection}} "{{slug}}"
    uploadMedia: CMS - Upload "{{path}}"
    deleteMedia: CMS - Delete "{{path}}"

media_folder: static/img
public_folder: /img

collections:
  - name: "configuration"
    label: "Configuration"
    editor:
      preview: false
    files:
      - file: "src/config/main.json"
        label: "Site Configuration"
        name: "config"
        fields:
          - {
              label: "Facebook Link",
              name: fb_link,
              widget: string,
              required: false,
            }
          - {
              label: "Instagram Link",
              name: ig_link,
              widget: string,
              required: false,
            }
  - name: "paintings"
    label: "Paintings"
    label_singular: "Painting"
    folder: "src/pages/paintings"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "painting-post.template",
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Is Reserved",
          name: "reserved",
          widget: "boolean",
          required: false,
          default: false,
        }
      - {
          label: "Is Sold",
          name: "sold",
          widget: "boolean",
          required: false,
          default: false,
        }
      - {
          label: "Is a copy",
          name: "copy",
          widget: "boolean",
          required: false,
          default: false,
        }
      - {
          label: "Price PLN",
          name: "price_pln",
          required: false,
          widget: "number",
        }
      - { label: "Measures", name: "measures", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page.template",
            }
          - { label: "Left Image", name: "left_image", widget: "image" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page.template",
            }
          - {
              label: "Store Link",
              name: "store_link",
              widget: "string",
              required: false,
            }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Contact Image", name: "image", widget: "image" }
